=== KatsiarynaMuzyka/Final-task/res/storage.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/storage"
	xmlns:tns="http://www.example.org/storage" elementFormDefault="qualified">

	<element name="tests">
		<complexType>
			<sequence>
				<element name="positive-test" type="tns:data" minOccurs="1"
					maxOccurs="10" />
					<element name="negative-test" type="tns:data" minOccurs="1"
					maxOccurs="10" />
			</sequence>
		</complexType>
	</element>

	<complexType name="data">
		<sequence>

			<element name="REGISTRATION-command" type="string" />
			<element name="AUTHORIZATION-command" type="string" />
			<element name="SHOW_SUBJECT-command" type="string" />
			<element name="GO_TESTING-command" type="string" />
			<element name="SHOW_QUESTION-command" type="string" />
			<element name="CREATE_NEW_QUESTION-command" type="string" />
			<element name="CREATE_NEW_SUBJECT-command" type="string" />
			<element name="subjectID" type="int" />
			<element name="login" type="string" />
			<element name="password" type="string" />
			<element name="answer" type="int" />
			<element name="question" type="string" />
			<element name="subjectName" type="string" />

		</sequence>

		<attribute name="id" use="required">
		</attribute>

	</complexType>


</schema>

=== KatsiarynaMuzyka/Final-task/res/storage.xml
<?xml version="1.0" encoding="UTF-8"?>

<tests 		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xmlns="http://www.example.org/storage"
			xsi:schemaLocation="http://www.example.org/storage storage.xsd">
	
	<positive-test id="1">
		
		<REGISTRATION-command>REGISTRATION</REGISTRATION-command>
		<AUTHORIZATION-command>LOGINATION</AUTHORIZATION-command>
		<SHOW_SUBJECT-command>SHOW_SUBJECT</SHOW_SUBJECT-command>
		<GO_TESTING-command>START_TEST</GO_TESTING-command>
		<SHOW_QUESTION-command>SHOW_QUESTION</SHOW_QUESTION-command>
		<CREATE_NEW_QUESTION-command>CREATE_NEW_QUESTION</CREATE_NEW_QUESTION-command>
		<CREATE_NEW_SUBJECT-command>CREATE_NEW_SUBJECT</CREATE_NEW_SUBJECT-command>
		<subjectID>1</subjectID>
		<login>NewUser</login>
		<password>qwerty</password>
		<answer>3</answer>
		<question>Решите уравнение: x=2x-150
		1. x = 50
		2. x = -150
		3. x = 150
		4. x = -50</question>
		<subjectName>Math</subjectName>
	
	</positive-test>
	
	<negative-test id="2">

		<REGISTRATION-command>REGISTRATION</REGISTRATION-command>
		<AUTHORIZATION-command>AUTHORIZATION</AUTHORIZATION-command>
		<SHOW_SUBJECT-command>SHOW_SUBJECT</SHOW_SUBJECT-command>
		<GO_TESTING-command>GO_TESTING</GO_TESTING-command>
		<SHOW_QUESTION-command>SHOW_QUESTION</SHOW_QUESTION-command>
		<CREATE_NEW_QUESTION-command>CREATE_NEW_QUESTION</CREATE_NEW_QUESTION-command>
		<CREATE_NEW_SUBJECT-command>CREATE_NEW_SUBJECT</CREATE_NEW_SUBJECT-command>
		<subjectID>0</subjectID>
		<login>Unknown</login>
		<password>qwerty</password>
		<answer>1</answer>
		<question></question>
		<subjectName> </subjectName>
	
	</negative-test>
	
	<negative-test id="3">
	
		<REGISTRATION-command>REGISTRATION</REGISTRATION-command>
		<AUTHORIZATION-command>AUTHORIZATION</AUTHORIZATION-command>
		<SHOW_SUBJECT-command>SHOW_SUBJECT</SHOW_SUBJECT-command>
		<GO_TESTING-command>GO_TESTING</GO_TESTING-command>
		<SHOW_QUESTION-command>SHOW_QUESTION</SHOW_QUESTION-command>
		<CREATE_NEW_QUESTION-command>CREATE_NEW_QUESTION</CREATE_NEW_QUESTION-command>
		<CREATE_NEW_SUBJECT-command>CREATE_NEW_SUBJECT</CREATE_NEW_SUBJECT-command>
		<subjectID>0</subjectID>
		<login>Unknown</login>
		<password>qwerty</password>
		<answer>5</answer>
		<question></question>
		<subjectName> </subjectName>
	
	</negative-test>

</tests>
